//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using Org.BouncyCastle.Crypto.Tls;
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int id_item { get; set; }
        public string name { get; set; }
        public string brand { get; set; }
        public double price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string importer { get; set; }
        public Nullable<bool> available { get; set; }
        public int storage_id { get; set; }
    
        public virtual storage storage { get; set; }

        public item()
        {

        }

        public item(string name,string brand,double price,int quantity,bool isAvailable,int storageId):this()
        {
            this.name = name;
            this.brand = brand;
            this.price = price;
            this.quantity = quantity;
            this.available = isAvailable;
            this.storage_id = storageId;
        }
    }
}
