//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class item
    {
        public int id_item { get; set; }
        public string name { get; set; }
        public string brand { get; set; }
        public double price { get; set; }
        public Nullable<int> quantity { get; set; }
        public string importer { get; set; }
        public Nullable<bool> available { get; set; }
        public int storage_id { get; set; }
    
        public virtual storage storage { get; set; }
    }
}
