//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class staff
    {
        public int id_staff { get; set; }
        public string first_name { get; set; }
        public string last_name { get; set; }
        public string email { get; set; }
        public string username { get; set; }
        public string password { get; set; }
        public int storage_id { get; set; }
    
        public virtual storage storage { get; set; }

        public staff()
        {

        }
        public staff(string first_name, string last_name, string email, string username, string password, int storage_id):this()
        {
            this.first_name = first_name;
            this.last_name = last_name;
            this.email = email;
            this.username = username;
            this.password = password;
            this.storage_id = storage_id;
        }
    }
}
